=== opendxl/opendxl-api-specification/schemas/v0.1/schema.json
{
  "title": "OpenDXL API Schema",
  "id": "https://opendxl.github.io/opendxl-api-specification/v0.1/schema.json#",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "required": [
    "openDxlApi",
    "info"
  ],
  "definitions": {
    "stringArray": {
      "description": "Similar to the stringArray definition in JSON Schema Draft 4 but allows for the array to be empty",
      "type": "array",
      "items": {
        "type": "string"
      },
      "uniqueItems": true,
      "default": []
    },
    "otherField": {
      "type": "object",
      "description": "An individual 'other field' in a DXL message. See 'otherFields' in the 'message' property.",
      "properties": {
        "description": {
          "$ref": "http://json-schema.org/draft-04/schema#/properties/description"
        },
        "example": {
          "description": "Example value for this 'other field'",
          "type": "string"
        },
        "required": {
          "type": "boolean",
          "description": "Determines whether or not this other field is required or optional.",
          "default": false
        }
      },
      "additionalProperties": false
    },
    "message": {
      "type": "object",
      "description": "Common properties for all messages which can be sent on a DXL fabric",
      "properties": {
        "payload": {
          "$ref": "http://swagger.io/v2/schema.json#/definitions/schema"
        },
        "otherFields": {
          "type": "object",
          "description": "The 'other fields' which can appear in a DXL message. 'other fields' add 'header'-like name/value pairs without requiring modifications to be made to the payload.",
          "properties": {
            "additionalProperties": {
              "$ref": "#/definitions/otherField"
            }
          }
        },
        "description": {
          "$ref": "http://json-schema.org/draft-04/schema#/properties/description"
        },
        "externalDocs": {
          "$ref": "http://swagger.io/v2/schema.json#/definitions/externalDocs"
        }
      }
    },
    "response": {
      "description": "A 'response' message which can be sent in response to a 'request' message sent on a DXL fabric",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/message"
        }
      ]
    },
    "request": {
      "description": "A 'request' message which can be sent on a DXL fabric",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/message"
        },
        {
          "type": "object",
          "properties": {
            "response": {
              "$ref": "#/definitions/response"
            },
            "alternateResponses": {
              "description": "Map of string identifiers/names to corresponding alternative responses to this request. This is used in cases where a request that matches the provided schema is capable of producing responses with different payload structures depending on the request content or the service's processing.",
              "type": "object",
              "patternProperties": {
                "*": {
                  "$ref": "#/definitions/response"
                }
              },
              "additionalProperties": false
            },
            "errorResponses": {
              "description": "Map of integer-based error codes to corresponding 'response' objects. The map describes the possible DXL error response messages which can be returned for a failed request.",
              "type": "object",
              "patternProperties": {
                "^-?[0-9]+$": {
                  "$ref": "#/definitions/response"
                }
              },
              "additionalProperties": false
            }
          }
        }
      ]
    },
    "requests": {
      "description": "A map of DXL request topic names to corresponding 'request' objects",
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/request"
      }
    },
    "event": {
      "description": "An event message which can be sent on a DXL fabric",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/message"
        },
        {
          "type": "object",
          "properties": {
            "isIncoming": {
              "type": "boolean",
              "description": "Whether this event is received (incoming) or sent by the solution.",
              "default": false
            }
          }
        }
      ]
    },
    "events": {
      "description": "A map of DXL event topic names to corresponding 'event' objects",
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/event"
      }
    },
    "serviceMetadataItem": {
      "type": "object",
      "description": "An individual 'item' in a DXL service 'metadata' object. See 'metadata' in the 'service' property.",
      "properties": {
        "description": {
          "$ref": "http://json-schema.org/draft-04/schema#/properties/description"
        },
        "example": {
          "description": "Example value for this metadata item",
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "service": {
      "description": "Information for a service registered with a DXL fabric",
      "type": "object",
      "properties": {
        "info": {
          "$ref": "http://swagger.io/v2/schema.json#/definitions/info"
        },
        "externalDocs": {
          "$ref": "http://swagger.io/v2/schema.json#/definitions/externalDocs"
        },
        "requests": {
          "description": "A map of DXL request topic names to corresponding request definitions under '#/requests' in this document",
          "type": "array",
          "items" : {
            "type": "object",
            "allOf": [
              {
                "$ref": "http://swagger.io/v2/schema.json#/definitions/jsonReference"
              },
              {
                "properties": {
                  "$ref": {
                    "pattern": "^#/requests/[^/]+"
                  }
                }
              }
            ]
          }
        },
        "metadata": {
          "description": "Metadata which can be registered with the DXL service. The metadata is typically used to include information such as the versions for products that are exposing DXL services, etc.",
          "type": "object",
          "properties": {
            "additionalProperties": {
              "$ref": "#/definitions/serviceMetadataItem"
            }
          }
        }
      },
      "additionalProperties": false
    },
    "services": {
      "description": "A map of DXL 'service type' strings to corresponding 'service' objects",
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/service"
      }
    },
    "solution": {
      "description": "Information for an individual DXL solution",
      "type": "object",
      "properties": {
        "info": {
          "$ref": "http://swagger.io/v2/schema.json#/definitions/info"
        },
        "externalDocs": {
          "$ref": "http://swagger.io/v2/schema.json#/definitions/externalDocs"
        },
        "events": {
          "description": "A map of DXL event topic names to corresponding event definitions under '#/events' in this document",
          "type": "array",
          "items" : {
            "type": "object",
            "allOf": [
              {
                "$ref": "http://swagger.io/v2/schema.json#/definitions/jsonReference"
              },
              {
                "properties": {
                  "$ref": {
                    "pattern": "^#/events/[^/]+"
                  }
                }
              }
            ]
          }
        },
        "services": {
          "description": "A map of DXL 'service type' strings to corresponding service definitions under '#/services' in this document",
          "type": "array",
          "items" : {
            "type": "object",
            "allOf": [
              {
                "$ref": "http://swagger.io/v2/schema.json#/definitions/jsonReference"
              },
              {
                "properties": {
                  "$ref": {
                    "pattern": "^#/services/[^/]+"
                  }
                }
              }
            ]
          }
        }
      },
      "additionalProperties": false
    }
  },
  "properties": {
    "openDxlApi": {
      "description": "The OpenDXL API version of this document",
      "type": "string",
      "enum": [
        "0.1"
      ]
    },
    "info": {
      "$ref": "http://swagger.io/v2/schema.json#/definitions/info"
    },
    "externalDocs": {
      "$ref": "http://swagger.io/v2/schema.json#/definitions/externalDocs"
    },
    "definitions": {
      "$ref": "http://swagger.io/v2/schema.json#/definitions/definitions"
    },
    "events": {
      "$ref": "#/definitions/events"
    },
    "requests": {
      "$ref": "#/definitions/requests"
    },
    "services": {
      "$ref": "#/definitions/services"
    },
    "solutions": {
      "description": "A map of DXL solution names to corresponding 'solution' objects",
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/solution"
      }
    }
  },
  "additionalProperties": false
}

=== opendxl/opendxl-api-specification/examples/v0.1/json/acme.json
{
  "openDxlApi": "0.1",
  "externalDocs": {
    "url": "https://www.opendxl.com/index.php?user/777-kaiotee/"
  },
  "info": {
    "title": "ACME OpenDXL Solutions",
    "version": "1.2.3",
    "description": "Wily tools for capturing the most elusive threats.",
    "contact": {
      "name": "Kai Otee",
      "url": "https://www.opendxl.com/index.php?user/777-kaiotee/",
      "email": "kai_otee@runningroads.com"
    }
  },
  "solutions": {
    "ACME Anvil Solution": {
      "info": {
        "title": "ACME Anvil Solution",
        "version": "4.5.6",
        "description": "The ACME Anvil Solution"
      },
      "externalDocs": {
        "description": "External product guide document for the ACME Anvil product line.",
        "url": "https://www.opendxl.com/filebase/index.php?file/999-acme-dxl-solution/"
      },
      "services": [
        { "$ref": "#/services/ACME Anvil Service" }
      ],
      "events": [
        { "$ref": "#/events/~1opendxl-acme~1event~1runneralert" },
        { "$ref": "#/events/~1opendxl-acme~1event~1cliffalert" },
        { "$ref": "#/events/~1opendxl-acme~1event~1runnerfree" }
      ]
    }
  },
  "services": {
    "ACME Anvil Service": {
      "info": {
        "title": "ACME Anvil Service",
        "version": "7.8.9",
        "description": "A service that supports alerts and drops."
      },
      "externalDocs": {
        "description": "External documentation describing design and usage of the ACME Anvil Service.",
        "url": "https://acme.github.io/acme-anvil-service/pydoc/acme-anvil-service.html"
      },
      "requests": [
        { "$ref": "#/requests/~1opendxl-acme~1service~1anvil~1alertregister" },
        { "$ref": "#/requests/~1opendxl-acme~1service~1anvil~1requestdrop" },
        { "$ref": "#/requests/~1opendxl-acme~1service~1anvil~1requestdropencrypted" }
      ],
      "metadata": {
        "anvilId": {
          "description": "ID for the anvils that this service manages.",
          "example": "12345"
        },
        "anvilType": {
          "description": "Type of anvils that this service manages.",
          "example": "Solid Steel"
        }
      }
    }
  },
  "events": {
    "/opendxl-acme/event/runneralert": {
      "description": "Alerts registered subscribers of a new detected Runner.",
      "payload": {
        "properties": {
          "runnerID": {
            "description": "ID for the runner that triggered this alert event.",
            "type": "integer"
          },
          "detectTime": {
            "description": "Time at which the specified runner was detected.",
            "type": "string",
            "format": "date-time"
          },
          "previousCaptureAttempted": {
            "description": "Whether or not there has been an attempt to capture this runner in the past.",
            "type": "boolean"
          }
        },
        "example": {
          "runnerID": 3,
          "detectTime": "2018-10-12T16:39:57-08:00",
          "previousCaptureAttempted": true
        }
      }
    },
    "/opendxl-acme/event/cliffalert": {
      "description": "Alerts registered subscribers of an imminent cliff detection.",
      "payload": {
        "properties": {
          "altitude": {
            "description": "Altitude of the incoming drop.",
            "type": "integer"
          },
          "timeUntilDetection": {
            "description": "Number of seconds until the cliff is detected.",
            "type": "integer"
          }
        },
        "example": {
          "runnerID": 3,
          "timeUntilDetection": "2018-10-14T12:23:35-02:13"
        }
      },
      "isIncoming": false
    },
    "/opendxl-acme/event/runnerfree": {
      "description": "Incoming event notifying ACME Anvil Solution that a previously-detected runner has been freed.",
      "payload": {
        "properties": {
          "runnerID": {
            "description": "ID for the runner that has been freed.",
            "type": "integer"
          },
          "timeFreed": {
            "description": "Time at which the specified runner was freed.",
            "type": "string",
            "format": "date-time"
          }
        },
        "example": {
          "runnerID": 3,
          "timeFreed": "2018-10-14T12:25:11-02:15"
        }
      },
      "isIncoming": true
    }
  },
  "requests": {
    "/opendxl-acme/service/anvil/alertregister": {
      "description": "Registers client GUID with ACME Anvil Service for Runner Alert events. Empty payload, does not return a response.",
      "payload": {
        "$ref": "#/definitions/alertRegisterPayload"
      }
    },
    "/opendxl-acme/service/anvil/requestdrop": {
      "description": "Requests ACME Anvil Service data drop for the specified target file.",
      "payload": {
        "$ref": "#/definitions/anvilRequestPayload"
      },
      "response": {
        "payload": {
          "$ref": "#/definitions/anvilResponsePayload"
        }
      },
      "errorResponses": {
        "1": {
          "description": "Unknown target.",
          "payload": {
            "properties": {
              "detailedErrorInfo": {
                "type": "string"
              }
            }
          }
        }
      },
      "externalDocs": {
        "description": "ACME Anvil Service Wiki: Data drop values and error response codes.",
        "url": "https://acmesolutions.com/specs/opendxl/anvil_request"
      }
    },
    "/opendxl-acme/service/anvil/requestdropencrypted": {
      "description": "Requests an encrypted ACME Anvil Service data drop for the specified target file.",
      "payload": {
        "example": {}
      },
      "response": {
        "payload": {
          "description": "Raw encrypted data drop.",
          "type": "string",
          "format": "binary"
        },
        "otherFields": {
          "publicKey": {
            "description": "Public key for the encrypted data drop.",
            "required": true,
            "example": "cf23df2207d99a74fbe169e3eba035e633b65d94"
          }
        }
      }
    }
  },
  "definitions": {
    "anvilRequestPayload": {
      "type": "object",
      "properties": {
        "targetID": {
          "description": "Target ID for file data.",
          "type": "string"
        }
      },
      "example": {
        "targetID": "roadRunner.exe"
      }
    },
    "anvilResponsePayload": {
      "type": "object",
      "properties": {
        "targetID": {
          "description": "Target ID for file data.",
          "type": "string"
        },
        "accuracy": {
          "description": "General measure of targeted Anvil data drop accuracy.",
          "type": "number",
          "format": "float"
        },
        "velocity": {
          "description": "The velocity of the target.",
          "type": "string"
        }
      },
      "example": {
        "targetID": "roadRunner.exe",
        "accuracy": 99.99,
        "velocity": "643 kph"
      }
    },
    "alertRegisterPayload": {
      "example": {}
    }
  }
}
